#!/bin/sh

WAIT_MSG="Waiting"
END_MSG="Done!"
declare -a CMD
ISDONE=$(mktemp done-XXXX)
INFO=$(mktemp info-XXXX)
VERBOSE=""
DELAY=0.2

# parse arguments
while [ -n "$1" ]
do
	case $1 in
		-w|--wait-msg) 
			WAIT_MSG=$2
			shift 1;;
		-e|--end-msg)
			END_MSG=$2
			shift 1;;
		-v|--verbose) VERBOSE=TRUE;;
		*) CMD+="$1 ";;
	esac
	shift 1
done

# set formatting of time info
export TIME="Time taken: %E\nMemory used: %Mkb"
# run the command
(env time $CMD 2> $INFO && echo "Done" > $ISDONE) &

if [ -n "$VERBOSE" ]
then
	printf "\x1b[1m-> $CMD\x1b[0m\n"
fi

# display a sorrento/loading spinner
while true
do
	printf "$WAIT_MSG | \r"
	sleep $DELAY
	printf "$WAIT_MSG / \r"
	sleep $DELAY
	printf "$WAIT_MSG - \r"
	sleep $DELAY
	printf "$WAIT_MSG \\ \r"
	sleep $DELAY
	if [ -n "$(cat $ISDONE)" ]
	then
		printf "\n$END_MSG\n"
		if [ -n "$VERBOSE" ]
		then
			printf "\n"
			cat $INFO
			printf "\x1b[1m+++\x1b[0m\n"
		fi
		echo "" > $ISDONE
		break
	fi
done

rm $ISDONE
rm $INFO
