#!/bin/sh

STALE_CMD=$(cat $HOME/.bash_history* | fzf)
read -p "About to run >>$STALE_CMD<<. Proceed (y/n)? " PPROCEED
if [ $PPROCEED = 'y' ]
then
    eval $STALE_CMD
else
    echo "...well, I guess we're not doing that then"
fi
