#!/bin/sh

# cursed
# resolution="$(xrandr | grep -F '*' | cut -d' ' -f 4)"

case $1 in
	-h|--help)
		cat <<-EOF
		rewallpaper, a wallpaper-changing script

		Usage:
		    rewallpaper {no arguments}
		List available wallpapers and let you select one to be the new wallpaper
		using fzf. Should automatically detect how to set wallpaper, using one of:
		  - swaybg (wayland)
		  - feh (X11)
		  - plasma-apply-wallpaperimage (KDE Plasma desktop - could be X11 or wayland)
		DOES NOT automatically detect display resolution.
		Currently searches for wallpapers in ~/Pictures/Profile_Pics and 
		/usr/share/wallpapers.
		    rewallpaper FILE_PATH
		Sets the wallpaper to the image at FILE_PATH. FILE_PATH must be absolute.
		Detets setting method same as above.
		EOF
		exit 0
		;;
	*) new_wallpaper=$1;;
esac

swaybg_wrap() {
	swaybg --mode stretch --image $1 & disown
	echo "swaybg --mode stretch --image $1 & disown" > ~/.swaybg
	chmod +x ~/.swaybg
}
	
# decide how to set wallpaper
cmd='feh --bg-fill'
if [ "$XDG_CURRENT_DESKTOP" = KDE ]
then
	cmd='plasma-apply-wallpaperimage --fill-mode preserveAspectCrop'
elif pgrep swaybg 2>&1 >/dev/null
then
	cmd=swaybg_wrap
fi

# detect whether new wallpaper has been set manually, and if not, find it
if [ -z "$new_wallpaper" ]
then
	personal=$(find -L $HOME/Pictures/Profile_Pics -type f)
	desktops=$(find -L /usr/share/wallpapers -type f -name '1920x1080*' -o -name '5120x2880*')
		# this line broke when split
	new_wallpaper=$(echo -e "$personal\n$desktops" | fzf)
fi

# set wallpaper, if possible
if [ -z "$new_wallpaper" ]
then
	echo "No wallpaper selected!" >&2
	exit 1
else
	$cmd $new_wallpaper
	echo -e "Wallpaper set to >>\e[1m$new_wallpaper\e[0m<<"
fi
