#!/bin/sh

swaybg_mode=stretch
gui_type=x11
screen_resolution='1920x1080'

while :
do
	case $1 in
		-h|--help)
			cat <<- EOF
			rewallpaper, a wallpaper-changing script
			
			Flags:
			    -g|--gui-type x11|wayland
			Specify whether to use feh (x11) or swaybg (wayland) to set the wallpaper
			    -m|--mode SWAYBG_MODE
			Passes the argument on to the falg of the same name f swaybg.
			Defaults to "stretch"
			    -r|--resolution MONITOR_RESOLUTION
			The monitor resolution in pixels, in the format {width}x{height},
			E.g. 1920x1080.
			EOF
			exit 0;;
		-m|--mode)
			swaybg_mode=$2
			shift 1;;
		-g|--gui-type)
			gui_type=$2
			shift 1;;
		-r|--resolution)
			screen_resolution=$2
			shift 1;;
		*) name=$1;;
	esac
	if [ -z "$@" ]
	then
		break
	fi
	shift 1
done


personal=$(find -L $HOME/Pictures/Profile_Pics -type f)
desktops=$(find -L /usr/share/wallpapers -type f -name '1920x1080*' -o -name '5120x2880*')

new_wallpaper=$(echo -e "$personal\n$desktops" | fzf)

if [ -z "$new_wallpaper" ]
then
	echo "No wallpaper selected!"
	exit 0
fi

case $gui_type in
	wayland)
		swaybg --image "$new_wallpaper" --mode "$swaybg_mode" & disown;;
	x11)
		feh --bg-fill "$new_wallpaper";;
esac

echo "Set wallpaper to $new_wallpaper!"
